### PR TITLE
Testable

### PR DESCRIPTION
**Pull request by rienafairefr**
A big refactor so that we can test the create_* functions with ynab client easily mockable

### CODE REVIEW

**Comment by scottrobertson** [comment]
Awesome, thanks! I will test this out today and get it merged. This makes adding backgrounding of the work much easier!

**Comment by scottrobertson** [comment]
```
[OKAY] Loaded ENV .env File as KEY=VALUE Format
11:51:14 PM web.1 |  Traceback (most recent call last):
11:51:14 PM web.1 |    File "python/main.py", line 5, in <module>
11:51:14 PM web.1 |      from routes import main_blueprints
11:51:14 PM web.1 |    File "fintech-to-ynab/python/routes.py", line 5, in <module>
11:51:14 PM web.1 |      from functions import create_transaction_from_monzo,create_transaction_from_starling
11:51:14 PM web.1 |    File "fintech-to-ynab/python/functions.py", line 7, in <module>
11:51:14 PM web.1 |      from python import ynab_client as ynab_client_module, settings as settings_module
11:51:14 PM web.1 |  ImportError: No module named python
```

@rienafairefr when i try and run this, i get the above error.

**Comment by scottrobertson** [comment]
Changing 

```
from python import ynab_client as ynab_client_module, settings as settings_module
```

to

```
import ynab_client as ynab_client_module, settings as settings_module
```

fixes it

**Comment by scottrobertson** [comment]
```
11:54:06 PM web.1 |    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
11:54:06 PM web.1 |      response = self.full_dispatch_request()
11:54:06 PM web.1 |    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
11:54:06 PM web.1 |      rv = self.handle_user_exception(e)
11:54:06 PM web.1 |    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
11:54:06 PM web.1 |      reraise(exc_type, exc_value, tb)
11:54:06 PM web.1 |    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
11:54:06 PM web.1 |      rv = self.dispatch_request()
11:54:06 PM web.1 |    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
11:54:06 PM web.1 |      return self.view_functions[rule.endpoint](**req.view_args)
11:54:06 PM web.1 |    File "fintech-to-ynab/python/routes.py", line 31, in decorated_view
11:54:06 PM web.1 |      return func(*args, **kwargs)
11:54:06 PM web.1 |    File "fintech-to-ynab/python/routes.py", line 51, in route_monzo
11:54:06 PM web.1 |      return common_view(create_transaction_from_monzo)
11:54:06 PM web.1 |    File "fintech-to-ynab/python/routes.py", line 40, in common_view
11:54:06 PM web.1 |      body, code = create_transaction_func(data, settings)
11:54:06 PM web.1 |    File "fintech-to-ynab/python/functions.py", line 91, in create_transaction_from_monzo
11:54:06 PM web.1 |      return {'error': 'Transaction amount is 0.'}, 200
11:54:06 PM web.1 |  KeyError: 'amount'
```

When posting a Monzo transaction.

**Comment by rienafairefr** [comment]
KeyError 'amoutn, taht might be from the line

    if data['amount'] == 0:
        return {'error': 'Transaction amount is 0.'}, 200

but it's not changed from the previous create_ function for monzo. You're testing it with a mock/fake data argument, or are you testing live on data that monzo sent ?

I'll add some kind of schema validation for the data argument maybe ?

**Comment by scottrobertson** [comment]
Hey

I am testing it with real data from Monzo.

**Comment by rienafairefr** [comment]
I've just added some debug statements to see the data received by the function. It looks like the data argument is wrong, maybe it's not de-json-ified correctly or something like that. Try to test with 9e7c0c5 and look at the debug statements "received data ***"

**Comment by scottrobertson** [comment]
```
9:59:15 AM web.1 |  DEBUG:settings:received data json {u'data': {u'originator': False, u'attachments': [], u'currency': u'GBP', u'id': u'tx_1', u'account_id': u'acc_0', u'category': u'mondo', u'is_load': True, u'scheme': u'gps_mastercard', u'dedupe_id': u'0', u'metadata': {u'stripe_card_last_four': u'1234', u'is_topup': u'true', u'stripe_charge_id': u'ch_1'}, u'merchant': None, u'updated': u'2017-06-08T11:34:53.548Z', u'account_balance': 11952, u'counterparty': {}, u'description': u'Top up', u'local_currency': u'GB
9:59:15 AM web.1 |  >  P', u'created': u'2017-06-07T11:34:53.15Z', u'settled': u'2017-06-08T11:34:53.15Z', u'notes': u'', u'include_in_spending': False, u'amount': 10000, u'local_amount': 10000}, u'type': u'transaction.created'}
9:59:15 AM web.1 |  DEBUG:settings:received post data {"type":"transaction.created","data":{"id":"tx_1","created":"2017-06-07T11:34:53.15Z","description":"Top up","amount":10000,"currency":"GBP","merchant":null,"notes":"","metadata":{"is_topup":"true","stripe_card_last_four":"1234","stripe_charge_id":"ch_1"},"account_balance":11952,"attachments":[],"category":"mondo","is_load":true,"settled":"2017-06-08T11:34:53.15Z","local_amount":10000,"local_currency":"GBP","updated":"2017-06-08T11:34:53.548Z","account_id":"acc_
9:59:15 AM web.1 |  >  0","counterparty":{},"scheme":"gps_mastercard","dedupe_id":"0","originator":false,"include_in_spending":false}}
9:59:15 AM web.1 |  DEBUG:settings:{u'data': {u'originator': False, u'attachments': [], u'currency': u'GBP', u'id': u'tx_1', u'account_id': u'acc_0', u'category': u'mondo', u'is_load': True, u'scheme': u'gps_mastercard', u'dedupe_id': u'0', u'metadata': {u'stripe_card_last_four': u'1234', u'is_topup': u'true', u'stripe_charge_id': u'ch_1'}, u'merchant': None, u'updated': u'2017-06-08T11:34:53.548Z', u'account_balance': 11952, u'counterparty': {}, u'description': u'Top up', u'local_currency': u'GBP', u'created': u'2
9:59:15 AM web.1 |  >  017-06-07T11:34:53.15Z', u'settled': u'2017-06-08T11:34:53.15Z', u'notes': u'', u'include_in_spending': False, u'amount': 10000, u'local_amount': 10000}, u'type': u'transaction.created'}
```

**Comment by rienafairefr** [comment]
OK the POST data we get is `{'data':[stuff],'type':'transaction.created'}` , and previously it was treated using the `data['data']` as argument, of course.

**Comment by rienafairefr** [comment]
aa5f506 should solve that

**Comment by scottrobertson** [comment]
There we go 👍 awesome job!

How do i run these tests out of interest?

**Comment by rienafairefr** [comment]
you can add a `python -m unittest discover` tests step in CI and that should cover all :-)

**Pull request merged**
